HHdata <- read.table("household_power_consumption.txt", sep = ";")
library(dplyr)
SSD <- filter(HHdata,HHdata$V1 == "1/2/2007" | HHdata$V1 == "2/2/2007")
write.csv(SSD, "SSD.csv")
r <- read.csv("SSD.csv")
png(file="plot1.png", width = 480, height = 480)
V3 <- as.numeric(r$V3)
hist(V3, col = "red", xaxt= c("n"),xlim = c(0,8), xlab = "Global Active Power (Kilowatts)" ,ylim= c(0,1200),ylab = "Frequency", main = "Global Active Power")
myTicks<-c(0,2,4,6)
axis(side=1,at=myTicks)
dev.off()